[project]
name = "agentic-tool-langgraph-kn"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "langchain",
    "python-dotenv",
    "ipykernel",
    "langchain_community",
    "pypdf",
    "bs4",
    
]
